plugins {
    id 'application'
    id 'distribution'
    //id 'org.cyclonedx.bom' version '3.0.0-alpha-1'
}

// Documentation source and destination
def exSrc   = file('src/examples')
def docSrc  = file('src/doc')
def docDist = layout.buildDirectory.dir('doc')

repositories {
    mavenCentral()
}

compileJava {
    options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
}

dependencies {
    implementation project(':lib-cmf')
    implementation project(':lib-util')
    implementation 'org.jcommander:jcommander:2.0'
    implementation 'commons-io:commons-io:2.18.0'
    implementation 'org.apache.commons:commons-lang3:3.17.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.24.3'
    implementation 'org.apache.logging.log4j:log4j-api:2.24.3'
}

application {
    applicationName = 'cmftool'
    mainClass = 'org.mitre.niem.cmftool.CMFTool'
}

distributions {
    main {
        distributionBaseName = 'cmftool'
        contents {
          into('doc')      { from(docDist) }
          into('examples') { from(exSrc) }
        }
    }
}

jar {
    manifest {
        attributes 'Implementation-Version': String.format('%s (%tF)', project.version, java.time.LocalDateTime.now()),
                   'Implementation-Title': 'CMFTool'
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.register('generateDocs') {
    description = 'Generate HTML from markdown'
    group = 'documentation'

    inputs.files fileTree(docSrc) { include '**/*.md' }
    outputs.dir docDist

    doLast {
        def execOps = services.get(org.gradle.process.ExecOperations)
        def outDir = docDist.get().asFile
        outDir.mkdirs()

        fileTree(docSrc) { include '**/*.md' }.each { File md ->
            def relPath  = docSrc.toPath().relativize(md.toPath()).toString()
            def htmlFile = new File(outDir, relPath.replaceAll(/\.md$/, '.html'))

            htmlFile.parentFile.mkdirs()

            println "Converting ${md.name} -> ${htmlFile.name}"

            execOps.exec {
                commandLine 'pandoc', '-f', 'gfm', '-t', 'html',
                            md.absolutePath, '-o', htmlFile.absolutePath
            }
        }
    }
}

tasks.named('installDist') { dependsOn 'generateDocs' }
tasks.named('distZip')     { dependsOn 'generateDocs' }
tasks.named('distTar')     { dependsOn 'generateDocs' }
    