//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.07 at 03:04:07 PM EDT 
//


package org.mitre.niem.nmf;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.mitre.niem.nmf.impl.ComponentTypeEx;


/**
 * A data type for a data type.
 * 
 * <p>Java class for DatatypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatatypeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://reference.niem.gov/specification/metamodel/5.0alpha1}ComponentType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}RestrictionOf" minOccurs="0"/&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}UnionOf" minOccurs="0"/&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}DatatypeAugmentationPoint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatatypeType", propOrder = {
    "restrictionOf",
    "unionOf",
    "datatypeAugmentationPoint"
})
public class DatatypeType
    extends ComponentTypeEx
{

    @XmlElement(name = "RestrictionOf", nillable = true)
    protected RestrictionOfType restrictionOf;
    @XmlElement(name = "UnionOf", nillable = true)
    protected UnionOfType unionOf;
    @XmlElement(name = "DatatypeAugmentationPoint")
    protected List<Object> datatypeAugmentationPoint;

    /**
     * Gets the value of the restrictionOf property.
     * 
     * @return
     *     possible object is
     *     {@link RestrictionOfType }
     *     
     */
    public RestrictionOfType getRestrictionOf() {
        return restrictionOf;
    }

    /**
     * Sets the value of the restrictionOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestrictionOfType }
     *     
     */
    public void setRestrictionOf(RestrictionOfType value) {
        this.restrictionOf = value;
    }

    /**
     * Gets the value of the unionOf property.
     * 
     * @return
     *     possible object is
     *     {@link UnionOfType }
     *     
     */
    public UnionOfType getUnionOf() {
        return unionOf;
    }

    /**
     * Sets the value of the unionOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnionOfType }
     *     
     */
    public void setUnionOf(UnionOfType value) {
        this.unionOf = value;
    }

    /**
     * Gets the value of the datatypeAugmentationPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the datatypeAugmentationPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatatypeAugmentationPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDatatypeAugmentationPoint() {
        if (datatypeAugmentationPoint == null) {
            datatypeAugmentationPoint = new ArrayList<Object>();
        }
        return this.datatypeAugmentationPoint;
    }

}
