//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.07 at 03:04:07 PM EDT 
//


package org.mitre.niem.nmf;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A data type for an occurrence of a data property within a class.
 * 
 * <p>Java class for HasDataPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HasDataPropertyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}DataProperty" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}HasDataPropertyAugmentationPoint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}minOccursQuantity"/&gt;
 *       &lt;attribute ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}maxOccursQuantity"/&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HasDataPropertyType", propOrder = {
    "dataProperty",
    "hasDataPropertyAugmentationPoint"
})
public class HasDataPropertyType
    extends ObjectType
{

    @XmlElement(name = "DataProperty", nillable = true)
    protected List<DataPropertyType> dataProperty;
    @XmlElement(name = "HasDataPropertyAugmentationPoint")
    protected List<Object> hasDataPropertyAugmentationPoint;
    @XmlAttribute(name = "minOccursQuantity", namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger minOccursQuantity;
    @XmlAttribute(name = "maxOccursQuantity", namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1")
    protected String maxOccursQuantity;

    /**
     * Gets the value of the dataProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the dataProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataPropertyType }
     * 
     * 
     */
    public List<DataPropertyType> getDataProperty() {
        if (dataProperty == null) {
            dataProperty = new ArrayList<DataPropertyType>();
        }
        return this.dataProperty;
    }

    /**
     * Gets the value of the hasDataPropertyAugmentationPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the hasDataPropertyAugmentationPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHasDataPropertyAugmentationPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getHasDataPropertyAugmentationPoint() {
        if (hasDataPropertyAugmentationPoint == null) {
            hasDataPropertyAugmentationPoint = new ArrayList<Object>();
        }
        return this.hasDataPropertyAugmentationPoint;
    }

    /**
     * Gets the value of the minOccursQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinOccursQuantity() {
        return minOccursQuantity;
    }

    /**
     * Sets the value of the minOccursQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinOccursQuantity(BigInteger value) {
        this.minOccursQuantity = value;
    }

    /**
     * Gets the value of the maxOccursQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxOccursQuantity() {
        return maxOccursQuantity;
    }

    /**
     * Sets the value of the maxOccursQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxOccursQuantity(String value) {
        this.maxOccursQuantity = value;
    }

}
