//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.07 at 03:04:07 PM EDT 
//


package org.mitre.niem.nmf;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A data type for a data model.
 * 
 * <p>Java class for ModelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModelType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}Class"/&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}DataProperty"/&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}Datatype"/&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}Namespace"/&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}ObjectProperty"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}ModelAugmentationPoint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelType", propOrder = {
    "clazzOrDataPropertyOrDatatype",
    "modelAugmentationPoint"
})
public class ModelType
    extends ObjectType
{

    @XmlElements({
        @XmlElement(name = "Class", type = ClassType.class, nillable = true),
        @XmlElement(name = "DataProperty", type = DataPropertyType.class, nillable = true),
        @XmlElement(name = "Datatype", type = DatatypeType.class, nillable = true),
        @XmlElement(name = "Namespace", type = NamespaceType.class, nillable = true),
        @XmlElement(name = "ObjectProperty", type = ObjectPropertyType.class, nillable = true)
    })
    protected List<ObjectType> clazzOrDataPropertyOrDatatype;
    @XmlElement(name = "ModelAugmentationPoint")
    protected List<Object> modelAugmentationPoint;

    /**
     * Gets the value of the clazzOrDataPropertyOrDatatype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the clazzOrDataPropertyOrDatatype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClazzOrDataPropertyOrDatatype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassType }
     * {@link DataPropertyType }
     * {@link DatatypeType }
     * {@link NamespaceType }
     * {@link ObjectPropertyType }
     * 
     * 
     */
    public List<ObjectType> getClazzOrDataPropertyOrDatatype() {
        if (clazzOrDataPropertyOrDatatype == null) {
            clazzOrDataPropertyOrDatatype = new ArrayList<ObjectType>();
        }
        return this.clazzOrDataPropertyOrDatatype;
    }

    /**
     * Gets the value of the modelAugmentationPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the modelAugmentationPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModelAugmentationPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getModelAugmentationPoint() {
        if (modelAugmentationPoint == null) {
            modelAugmentationPoint = new ArrayList<Object>();
        }
        return this.modelAugmentationPoint;
    }

}
