//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.07 at 03:04:07 PM EDT 
//


package org.mitre.niem.nmf;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.mitre.niem.nmf.impl.ComponentTypeEx;


/**
 * A data type for an object property
 * 
 * <p>Java class for ObjectPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectPropertyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://reference.niem.gov/specification/metamodel/5.0alpha1}ComponentType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}SubPropertyOf" minOccurs="0"/&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}Class" minOccurs="0"/&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}AbstractIndicator" minOccurs="0"/&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}ObjectPropertyAugmentationPoint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectPropertyType", propOrder = {
    "subPropertyOf",
    "clazz",
    "abstractIndicator",
    "objectPropertyAugmentationPoint"
})
public class ObjectPropertyType
    extends ComponentTypeEx
{

    @XmlElement(name = "SubPropertyOf", nillable = true)
    protected SubPropertyOfType subPropertyOf;
    @XmlElement(name = "Class", nillable = true)
    protected ClassType clazz;
    @XmlElement(name = "AbstractIndicator", nillable = true)
    protected Boolean abstractIndicator;
    @XmlElement(name = "ObjectPropertyAugmentationPoint")
    protected List<Object> objectPropertyAugmentationPoint;

    /**
     * Gets the value of the subPropertyOf property.
     * 
     * @return
     *     possible object is
     *     {@link SubPropertyOfType }
     *     
     */
    public SubPropertyOfType getSubPropertyOf() {
        return subPropertyOf;
    }

    /**
     * Sets the value of the subPropertyOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubPropertyOfType }
     *     
     */
    public void setSubPropertyOf(SubPropertyOfType value) {
        this.subPropertyOf = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link ClassType }
     *     
     */
    public ClassType getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassType }
     *     
     */
    public void setClazz(ClassType value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the abstractIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAbstractIndicator() {
        return abstractIndicator;
    }

    /**
     * Sets the value of the abstractIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAbstractIndicator(Boolean value) {
        this.abstractIndicator = value;
    }

    /**
     * Gets the value of the objectPropertyAugmentationPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the objectPropertyAugmentationPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjectPropertyAugmentationPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getObjectPropertyAugmentationPoint() {
        if (objectPropertyAugmentationPoint == null) {
            objectPropertyAugmentationPoint = new ArrayList<Object>();
        }
        return this.objectPropertyAugmentationPoint;
    }

}
