//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.07 at 03:04:07 PM EDT 
//


package org.mitre.niem.nmf;

import java.math.BigInteger;
import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mitre.niem.nmf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AbstractIndicator_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "AbstractIndicator");
    private final static QName _AnyValueAbstract_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "AnyValueAbstract");
    private final static QName _AnyValueFacetAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "AnyValueFacetAugmentationPoint");
    private final static QName _Class_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "Class");
    private final static QName _ModelItemAbstract_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "ModelItemAbstract");
    private final static QName _ClassAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "ClassAugmentationPoint");
    private final static QName _ComponentAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "ComponentAugmentationPoint");
    private final static QName _ContentStyleCode_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "ContentStyleCode");
    private final static QName _DataProperty_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "DataProperty");
    private final static QName _DataPropertyAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "DataPropertyAugmentationPoint");
    private final static QName _Datatype_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "Datatype");
    private final static QName _DatatypeAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "DatatypeAugmentationPoint");
    private final static QName _DefinitionText_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "DefinitionText");
    private final static QName _Enumeration_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "Enumeration");
    private final static QName _FacetAbstract_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "FacetAbstract");
    private final static QName _ExtensionOf_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "ExtensionOf");
    private final static QName _ExtensionOfAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "ExtensionOfAugmentationPoint");
    private final static QName _FractionDigits_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "FractionDigits");
    private final static QName _HasDataProperty_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "HasDataProperty");
    private final static QName _HasDataPropertyAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "HasDataPropertyAugmentationPoint");
    private final static QName _HasObjectProperty_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "HasObjectProperty");
    private final static QName _HasObjectPropertyAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "HasObjectPropertyAugmentationPoint");
    private final static QName _HasValue_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "HasValue");
    private final static QName _HasValueAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "HasValueAugmentationPoint");
    private final static QName _Length_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "Length");
    private final static QName _MaxExclusive_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "MaxExclusive");
    private final static QName _MaxInclusive_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "MaxInclusive");
    private final static QName _MaxLength_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "MaxLength");
    private final static QName _MinExclusive_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "MinExclusive");
    private final static QName _MinInclusive_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "MinInclusive");
    private final static QName _MinLength_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "MinLength");
    private final static QName _Model_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "Model");
    private final static QName _ModelAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "ModelAugmentationPoint");
    private final static QName _Name_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "Name");
    private final static QName _Namespace_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "Namespace");
    private final static QName _NamespacePrefixName_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "NamespacePrefixName");
    private final static QName _NamespaceAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "NamespaceAugmentationPoint");
    private final static QName _NamespaceURI_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "NamespaceURI");
    private final static QName _NonNegativeValue_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "NonNegativeValue");
    private final static QName _NonNegativeValueFacetAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "NonNegativeValueFacetAugmentationPoint");
    private final static QName _ObjectProperty_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "ObjectProperty");
    private final static QName _ObjectPropertyAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "ObjectPropertyAugmentationPoint");
    private final static QName _Pattern_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "Pattern");
    private final static QName _PatternFacetAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "PatternFacetAugmentationPoint");
    private final static QName _PositiveValue_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "PositiveValue");
    private final static QName _PositiveValueFacetAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "PositiveValueFacetAugmentationPoint");
    private final static QName _RestrictionOf_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "RestrictionOf");
    private final static QName _RestrictionOfAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "RestrictionOfAugmentationPoint");
    private final static QName _StringValue_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "StringValue");
    private final static QName _SubPropertyOf_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "SubPropertyOf");
    private final static QName _SubPropertyOfAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "SubPropertyOfAugmentationPoint");
    private final static QName _TotalDigits_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "TotalDigits");
    private final static QName _UnionOf_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "UnionOf");
    private final static QName _UnionOfAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "UnionOfAugmentationPoint");
    private final static QName _WhiteSpace_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "WhiteSpace");
    private final static QName _WhiteSpaceFacetAugmentationPoint_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "WhiteSpaceFacetAugmentationPoint");
    private final static QName _WhiteSpaceValueCode_QNAME = new QName("http://reference.niem.gov/specification/metamodel/5.0alpha1", "WhiteSpaceValueCode");
    private final static QName _ObjectAugmentationPoint_QNAME = new QName("http://release.niem.gov/niem/structures/5.0/", "ObjectAugmentationPoint");
    private final static QName _AssociationAugmentationPoint_QNAME = new QName("http://release.niem.gov/niem/structures/5.0/", "AssociationAugmentationPoint");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mitre.niem.nmf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClassType }
     * 
     */
    public ClassType createClassType() {
        return new ClassType();
    }

    /**
     * Create an instance of {@link DataPropertyType }
     * 
     */
    public DataPropertyType createDataPropertyType() {
        return new DataPropertyType();
    }

    /**
     * Create an instance of {@link DatatypeType }
     * 
     */
    public DatatypeType createDatatypeType() {
        return new DatatypeType();
    }

    /**
     * Create an instance of {@link AnyValueFacetType }
     * 
     */
    public AnyValueFacetType createAnyValueFacetType() {
        return new AnyValueFacetType();
    }

    /**
     * Create an instance of {@link ExtensionOfType }
     * 
     */
    public ExtensionOfType createExtensionOfType() {
        return new ExtensionOfType();
    }

    /**
     * Create an instance of {@link NonNegativeValueFacetType }
     * 
     */
    public NonNegativeValueFacetType createNonNegativeValueFacetType() {
        return new NonNegativeValueFacetType();
    }

    /**
     * Create an instance of {@link HasDataPropertyType }
     * 
     */
    public HasDataPropertyType createHasDataPropertyType() {
        return new HasDataPropertyType();
    }

    /**
     * Create an instance of {@link HasObjectPropertyType }
     * 
     */
    public HasObjectPropertyType createHasObjectPropertyType() {
        return new HasObjectPropertyType();
    }

    /**
     * Create an instance of {@link HasValueType }
     * 
     */
    public HasValueType createHasValueType() {
        return new HasValueType();
    }

    /**
     * Create an instance of {@link ModelType }
     * 
     */
    public ModelType createModelType() {
        return new ModelType();
    }

    /**
     * Create an instance of {@link NamespaceType }
     * 
     */
    public NamespaceType createNamespaceType() {
        return new NamespaceType();
    }

    /**
     * Create an instance of {@link ObjectPropertyType }
     * 
     */
    public ObjectPropertyType createObjectPropertyType() {
        return new ObjectPropertyType();
    }

    /**
     * Create an instance of {@link PatternFacetType }
     * 
     */
    public PatternFacetType createPatternFacetType() {
        return new PatternFacetType();
    }

    /**
     * Create an instance of {@link RestrictionOfType }
     * 
     */
    public RestrictionOfType createRestrictionOfType() {
        return new RestrictionOfType();
    }

    /**
     * Create an instance of {@link SubPropertyOfType }
     * 
     */
    public SubPropertyOfType createSubPropertyOfType() {
        return new SubPropertyOfType();
    }

    /**
     * Create an instance of {@link PositiveValueFacetType }
     * 
     */
    public PositiveValueFacetType createPositiveValueFacetType() {
        return new PositiveValueFacetType();
    }

    /**
     * Create an instance of {@link UnionOfType }
     * 
     */
    public UnionOfType createUnionOfType() {
        return new UnionOfType();
    }

    /**
     * Create an instance of {@link WhiteSpaceFacetType }
     * 
     */
    public WhiteSpaceFacetType createWhiteSpaceFacetType() {
        return new WhiteSpaceFacetType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "AbstractIndicator")
    public JAXBElement<Boolean> createAbstractIndicator(Boolean value) {
        return new JAXBElement<Boolean>(_AbstractIndicator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "AnyValueAbstract")
    public JAXBElement<Object> createAnyValueAbstract(Object value) {
        return new JAXBElement<Object>(_AnyValueAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "AnyValueFacetAugmentationPoint")
    public JAXBElement<Object> createAnyValueFacetAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_AnyValueFacetAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ClassType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "Class", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "ModelItemAbstract")
    public JAXBElement<ClassType> createClass(ClassType value) {
        return new JAXBElement<ClassType>(_Class_QNAME, ClassType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "ModelItemAbstract")
    public JAXBElement<Object> createModelItemAbstract(Object value) {
        return new JAXBElement<Object>(_ModelItemAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "ClassAugmentationPoint")
    public JAXBElement<Object> createClassAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_ClassAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "ComponentAugmentationPoint")
    public JAXBElement<Object> createComponentAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_ComponentAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContentStyleCodeSimpleType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ContentStyleCodeSimpleType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "ContentStyleCode")
    public JAXBElement<ContentStyleCodeSimpleType> createContentStyleCode(ContentStyleCodeSimpleType value) {
        return new JAXBElement<ContentStyleCodeSimpleType>(_ContentStyleCode_QNAME, ContentStyleCodeSimpleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataPropertyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DataPropertyType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "DataProperty", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "ModelItemAbstract")
    public JAXBElement<DataPropertyType> createDataProperty(DataPropertyType value) {
        return new JAXBElement<DataPropertyType>(_DataProperty_QNAME, DataPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "DataPropertyAugmentationPoint")
    public JAXBElement<Object> createDataPropertyAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_DataPropertyAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatatypeType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DatatypeType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "Datatype", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "ModelItemAbstract")
    public JAXBElement<DatatypeType> createDatatype(DatatypeType value) {
        return new JAXBElement<DatatypeType>(_Datatype_QNAME, DatatypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "DatatypeAugmentationPoint")
    public JAXBElement<Object> createDatatypeAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_DatatypeAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "DefinitionText")
    public JAXBElement<String> createDefinitionText(String value) {
        return new JAXBElement<String>(_DefinitionText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyValueFacetType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AnyValueFacetType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "Enumeration", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "FacetAbstract")
    public JAXBElement<AnyValueFacetType> createEnumeration(AnyValueFacetType value) {
        return new JAXBElement<AnyValueFacetType>(_Enumeration_QNAME, AnyValueFacetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "FacetAbstract")
    public JAXBElement<Object> createFacetAbstract(Object value) {
        return new JAXBElement<Object>(_FacetAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionOfType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ExtensionOfType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "ExtensionOf")
    public JAXBElement<ExtensionOfType> createExtensionOf(ExtensionOfType value) {
        return new JAXBElement<ExtensionOfType>(_ExtensionOf_QNAME, ExtensionOfType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "ExtensionOfAugmentationPoint")
    public JAXBElement<Object> createExtensionOfAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_ExtensionOfAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonNegativeValueFacetType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NonNegativeValueFacetType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "FractionDigits", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "FacetAbstract")
    public JAXBElement<NonNegativeValueFacetType> createFractionDigits(NonNegativeValueFacetType value) {
        return new JAXBElement<NonNegativeValueFacetType>(_FractionDigits_QNAME, NonNegativeValueFacetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HasDataPropertyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link HasDataPropertyType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "HasDataProperty")
    public JAXBElement<HasDataPropertyType> createHasDataProperty(HasDataPropertyType value) {
        return new JAXBElement<HasDataPropertyType>(_HasDataProperty_QNAME, HasDataPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "HasDataPropertyAugmentationPoint")
    public JAXBElement<Object> createHasDataPropertyAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_HasDataPropertyAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HasObjectPropertyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link HasObjectPropertyType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "HasObjectProperty")
    public JAXBElement<HasObjectPropertyType> createHasObjectProperty(HasObjectPropertyType value) {
        return new JAXBElement<HasObjectPropertyType>(_HasObjectProperty_QNAME, HasObjectPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "HasObjectPropertyAugmentationPoint")
    public JAXBElement<Object> createHasObjectPropertyAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_HasObjectPropertyAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HasValueType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link HasValueType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "HasValue")
    public JAXBElement<HasValueType> createHasValue(HasValueType value) {
        return new JAXBElement<HasValueType>(_HasValue_QNAME, HasValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "HasValueAugmentationPoint")
    public JAXBElement<Object> createHasValueAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_HasValueAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonNegativeValueFacetType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NonNegativeValueFacetType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "Length", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "FacetAbstract")
    public JAXBElement<NonNegativeValueFacetType> createLength(NonNegativeValueFacetType value) {
        return new JAXBElement<NonNegativeValueFacetType>(_Length_QNAME, NonNegativeValueFacetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyValueFacetType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AnyValueFacetType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "MaxExclusive", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "FacetAbstract")
    public JAXBElement<AnyValueFacetType> createMaxExclusive(AnyValueFacetType value) {
        return new JAXBElement<AnyValueFacetType>(_MaxExclusive_QNAME, AnyValueFacetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyValueFacetType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AnyValueFacetType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "MaxInclusive", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "FacetAbstract")
    public JAXBElement<AnyValueFacetType> createMaxInclusive(AnyValueFacetType value) {
        return new JAXBElement<AnyValueFacetType>(_MaxInclusive_QNAME, AnyValueFacetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonNegativeValueFacetType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NonNegativeValueFacetType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "MaxLength", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "FacetAbstract")
    public JAXBElement<NonNegativeValueFacetType> createMaxLength(NonNegativeValueFacetType value) {
        return new JAXBElement<NonNegativeValueFacetType>(_MaxLength_QNAME, NonNegativeValueFacetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyValueFacetType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AnyValueFacetType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "MinExclusive", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "FacetAbstract")
    public JAXBElement<AnyValueFacetType> createMinExclusive(AnyValueFacetType value) {
        return new JAXBElement<AnyValueFacetType>(_MinExclusive_QNAME, AnyValueFacetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyValueFacetType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AnyValueFacetType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "MinInclusive", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "FacetAbstract")
    public JAXBElement<AnyValueFacetType> createMinInclusive(AnyValueFacetType value) {
        return new JAXBElement<AnyValueFacetType>(_MinInclusive_QNAME, AnyValueFacetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonNegativeValueFacetType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NonNegativeValueFacetType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "MinLength", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "FacetAbstract")
    public JAXBElement<NonNegativeValueFacetType> createMinLength(NonNegativeValueFacetType value) {
        return new JAXBElement<NonNegativeValueFacetType>(_MinLength_QNAME, NonNegativeValueFacetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModelType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ModelType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "Model")
    public JAXBElement<ModelType> createModel(ModelType value) {
        return new JAXBElement<ModelType>(_Model_QNAME, ModelType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "ModelAugmentationPoint")
    public JAXBElement<Object> createModelAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_ModelAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "Name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamespaceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NamespaceType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "Namespace", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "ModelItemAbstract")
    public JAXBElement<NamespaceType> createNamespace(NamespaceType value) {
        return new JAXBElement<NamespaceType>(_Namespace_QNAME, NamespaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "NamespacePrefixName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNamespacePrefixName(String value) {
        return new JAXBElement<String>(_NamespacePrefixName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "NamespaceAugmentationPoint")
    public JAXBElement<Object> createNamespaceAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_NamespaceAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "NamespaceURI")
    public JAXBElement<String> createNamespaceURI(String value) {
        return new JAXBElement<String>(_NamespaceURI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "NonNegativeValue", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "AnyValueAbstract")
    public JAXBElement<BigInteger> createNonNegativeValue(BigInteger value) {
        return new JAXBElement<BigInteger>(_NonNegativeValue_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "NonNegativeValueFacetAugmentationPoint")
    public JAXBElement<Object> createNonNegativeValueFacetAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_NonNegativeValueFacetAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectPropertyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectPropertyType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "ObjectProperty", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "ModelItemAbstract")
    public JAXBElement<ObjectPropertyType> createObjectProperty(ObjectPropertyType value) {
        return new JAXBElement<ObjectPropertyType>(_ObjectProperty_QNAME, ObjectPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "ObjectPropertyAugmentationPoint")
    public JAXBElement<Object> createObjectPropertyAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_ObjectPropertyAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatternFacetType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PatternFacetType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "Pattern", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "FacetAbstract")
    public JAXBElement<PatternFacetType> createPattern(PatternFacetType value) {
        return new JAXBElement<PatternFacetType>(_Pattern_QNAME, PatternFacetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "PatternFacetAugmentationPoint")
    public JAXBElement<Object> createPatternFacetAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_PatternFacetAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "PositiveValue", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "AnyValueAbstract")
    public JAXBElement<BigInteger> createPositiveValue(BigInteger value) {
        return new JAXBElement<BigInteger>(_PositiveValue_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "PositiveValueFacetAugmentationPoint")
    public JAXBElement<Object> createPositiveValueFacetAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_PositiveValueFacetAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RestrictionOfType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RestrictionOfType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "RestrictionOf")
    public JAXBElement<RestrictionOfType> createRestrictionOf(RestrictionOfType value) {
        return new JAXBElement<RestrictionOfType>(_RestrictionOf_QNAME, RestrictionOfType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "RestrictionOfAugmentationPoint")
    public JAXBElement<Object> createRestrictionOfAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_RestrictionOfAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "StringValue", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "AnyValueAbstract")
    public JAXBElement<String> createStringValue(String value) {
        return new JAXBElement<String>(_StringValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubPropertyOfType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SubPropertyOfType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "SubPropertyOf")
    public JAXBElement<SubPropertyOfType> createSubPropertyOf(SubPropertyOfType value) {
        return new JAXBElement<SubPropertyOfType>(_SubPropertyOf_QNAME, SubPropertyOfType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "SubPropertyOfAugmentationPoint")
    public JAXBElement<Object> createSubPropertyOfAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_SubPropertyOfAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PositiveValueFacetType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PositiveValueFacetType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "TotalDigits", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "FacetAbstract")
    public JAXBElement<PositiveValueFacetType> createTotalDigits(PositiveValueFacetType value) {
        return new JAXBElement<PositiveValueFacetType>(_TotalDigits_QNAME, PositiveValueFacetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnionOfType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UnionOfType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "UnionOf")
    public JAXBElement<UnionOfType> createUnionOf(UnionOfType value) {
        return new JAXBElement<UnionOfType>(_UnionOf_QNAME, UnionOfType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "UnionOfAugmentationPoint")
    public JAXBElement<Object> createUnionOfAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_UnionOfAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WhiteSpaceFacetType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WhiteSpaceFacetType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "WhiteSpace", substitutionHeadNamespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", substitutionHeadName = "FacetAbstract")
    public JAXBElement<WhiteSpaceFacetType> createWhiteSpace(WhiteSpaceFacetType value) {
        return new JAXBElement<WhiteSpaceFacetType>(_WhiteSpace_QNAME, WhiteSpaceFacetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "WhiteSpaceFacetAugmentationPoint")
    public JAXBElement<Object> createWhiteSpaceFacetAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_WhiteSpaceFacetAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WhiteSpaceFacetCodeSimpleType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WhiteSpaceFacetCodeSimpleType }{@code >}
     */
    @XmlElementDecl(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", name = "WhiteSpaceValueCode")
    public JAXBElement<WhiteSpaceFacetCodeSimpleType> createWhiteSpaceValueCode(WhiteSpaceFacetCodeSimpleType value) {
        return new JAXBElement<WhiteSpaceFacetCodeSimpleType>(_WhiteSpaceValueCode_QNAME, WhiteSpaceFacetCodeSimpleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/structures/5.0/", name = "ObjectAugmentationPoint")
    public JAXBElement<Object> createObjectAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_ObjectAugmentationPoint_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://release.niem.gov/niem/structures/5.0/", name = "AssociationAugmentationPoint")
    public JAXBElement<Object> createAssociationAugmentationPoint(Object value) {
        return new JAXBElement<Object>(_AssociationAugmentationPoint_QNAME, Object.class, null, value);
    }

}
