//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.07 at 03:04:07 PM EDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.mitre.niem.nmf;
