//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.07 at 03:04:07 PM EDT 
//


package org.mitre.niem.nmf;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A data type for a facet that carries a value that is a positive integer.
 * 
 * <p>Java class for PositiveValueFacetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PositiveValueFacetType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}PositiveValue"/&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}DefinitionText"/&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}PositiveValueFacetAugmentationPoint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PositiveValueFacetType", propOrder = {
    "positiveValue",
    "definitionText",
    "positiveValueFacetAugmentationPoint"
})
public class PositiveValueFacetType
    extends ObjectType
{

    @XmlElement(name = "PositiveValue", required = true, nillable = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger positiveValue;
    @XmlElement(name = "DefinitionText", required = true, nillable = true)
    protected String definitionText;
    @XmlElement(name = "PositiveValueFacetAugmentationPoint")
    protected List<Object> positiveValueFacetAugmentationPoint;

    /**
     * Gets the value of the positiveValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPositiveValue() {
        return positiveValue;
    }

    /**
     * Sets the value of the positiveValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPositiveValue(BigInteger value) {
        this.positiveValue = value;
    }

    /**
     * Gets the value of the definitionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefinitionText() {
        return definitionText;
    }

    /**
     * Sets the value of the definitionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefinitionText(String value) {
        this.definitionText = value;
    }

    /**
     * Gets the value of the positiveValueFacetAugmentationPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the positiveValueFacetAugmentationPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPositiveValueFacetAugmentationPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getPositiveValueFacetAugmentationPoint() {
        if (positiveValueFacetAugmentationPoint == null) {
            positiveValueFacetAugmentationPoint = new ArrayList<Object>();
        }
        return this.positiveValueFacetAugmentationPoint;
    }

}
