//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.07 at 03:04:07 PM EDT 
//


package org.mitre.niem.nmf;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A data type for a restriction of a data type.
 * 
 * <p>Java class for RestrictionOfType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RestrictionOfType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}Datatype"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}Enumeration"/&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}FractionDigits"/&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}Length"/&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}MaxExclusive"/&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}MaxInclusive"/&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}MaxLength"/&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}MinExclusive"/&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}MinInclusive"/&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}MinLength"/&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}Pattern"/&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}TotalDigits"/&gt;
 *           &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}WhiteSpace"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}RestrictionOfAugmentationPoint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RestrictionOfType", propOrder = {
    "datatype",
    "enumerationOrFractionDigitsOrLength",
    "restrictionOfAugmentationPoint"
})
public class RestrictionOfType
    extends ObjectType
{

    @XmlElement(name = "Datatype", required = true, nillable = true)
    protected DatatypeType datatype;
    @XmlElementRefs({
        @XmlElementRef(name = "Enumeration", namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "FractionDigits", namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Length", namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "MaxExclusive", namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "MaxInclusive", namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "MaxLength", namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "MinExclusive", namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "MinInclusive", namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "MinLength", namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Pattern", namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TotalDigits", namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "WhiteSpace", namespace = "http://reference.niem.gov/specification/metamodel/5.0alpha1", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<? extends ObjectType>> enumerationOrFractionDigitsOrLength;
    @XmlElement(name = "RestrictionOfAugmentationPoint")
    protected List<Object> restrictionOfAugmentationPoint;

    /**
     * Gets the value of the datatype property.
     * 
     * @return
     *     possible object is
     *     {@link DatatypeType }
     *     
     */
    public DatatypeType getDatatype() {
        return datatype;
    }

    /**
     * Sets the value of the datatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatatypeType }
     *     
     */
    public void setDatatype(DatatypeType value) {
        this.datatype = value;
    }

    /**
     * Gets the value of the enumerationOrFractionDigitsOrLength property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the enumerationOrFractionDigitsOrLength property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnumerationOrFractionDigitsOrLength().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link AnyValueFacetType }{@code >}
     * {@link JAXBElement }{@code <}{@link NonNegativeValueFacetType }{@code >}
     * {@link JAXBElement }{@code <}{@link NonNegativeValueFacetType }{@code >}
     * {@link JAXBElement }{@code <}{@link AnyValueFacetType }{@code >}
     * {@link JAXBElement }{@code <}{@link AnyValueFacetType }{@code >}
     * {@link JAXBElement }{@code <}{@link NonNegativeValueFacetType }{@code >}
     * {@link JAXBElement }{@code <}{@link AnyValueFacetType }{@code >}
     * {@link JAXBElement }{@code <}{@link AnyValueFacetType }{@code >}
     * {@link JAXBElement }{@code <}{@link NonNegativeValueFacetType }{@code >}
     * {@link JAXBElement }{@code <}{@link PatternFacetType }{@code >}
     * {@link JAXBElement }{@code <}{@link PositiveValueFacetType }{@code >}
     * {@link JAXBElement }{@code <}{@link WhiteSpaceFacetType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends ObjectType>> getEnumerationOrFractionDigitsOrLength() {
        if (enumerationOrFractionDigitsOrLength == null) {
            enumerationOrFractionDigitsOrLength = new ArrayList<JAXBElement<? extends ObjectType>>();
        }
        return this.enumerationOrFractionDigitsOrLength;
    }

    /**
     * Gets the value of the restrictionOfAugmentationPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the restrictionOfAugmentationPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRestrictionOfAugmentationPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getRestrictionOfAugmentationPoint() {
        if (restrictionOfAugmentationPoint == null) {
            restrictionOfAugmentationPoint = new ArrayList<Object>();
        }
        return this.restrictionOfAugmentationPoint;
    }

}
