//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.07 at 03:04:07 PM EDT 
//


package org.mitre.niem.nmf;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A data type for a description of a subproperty.
 * 
 * <p>Java class for SubPropertyOfType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubPropertyOfType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}ObjectProperty"/&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}SubPropertyOfAugmentationPoint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubPropertyOfType", propOrder = {
    "objectProperty",
    "subPropertyOfAugmentationPoint"
})
public class SubPropertyOfType
    extends ObjectType
{

    @XmlElement(name = "ObjectProperty", required = true, nillable = true)
    protected ObjectPropertyType objectProperty;
    @XmlElement(name = "SubPropertyOfAugmentationPoint")
    protected List<Object> subPropertyOfAugmentationPoint;

    /**
     * Gets the value of the objectProperty property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectPropertyType }
     *     
     */
    public ObjectPropertyType getObjectProperty() {
        return objectProperty;
    }

    /**
     * Sets the value of the objectProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectPropertyType }
     *     
     */
    public void setObjectProperty(ObjectPropertyType value) {
        this.objectProperty = value;
    }

    /**
     * Gets the value of the subPropertyOfAugmentationPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the subPropertyOfAugmentationPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubPropertyOfAugmentationPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getSubPropertyOfAugmentationPoint() {
        if (subPropertyOfAugmentationPoint == null) {
            subPropertyOfAugmentationPoint = new ArrayList<Object>();
        }
        return this.subPropertyOfAugmentationPoint;
    }

}
