//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.07 at 03:04:07 PM EDT 
//


package org.mitre.niem.nmf;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A data type constraining how white space within data values is handled.
 * 
 * <p>Java class for WhiteSpaceFacetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WhiteSpaceFacetType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}WhiteSpaceValueCode"/&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}DefinitionText"/&gt;
 *         &lt;element ref="{http://reference.niem.gov/specification/metamodel/5.0alpha1}WhiteSpaceFacetAugmentationPoint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WhiteSpaceFacetType", propOrder = {
    "whiteSpaceValueCode",
    "definitionText",
    "whiteSpaceFacetAugmentationPoint"
})
public class WhiteSpaceFacetType
    extends ObjectType
{

    @XmlElement(name = "WhiteSpaceValueCode", required = true, nillable = true)
    @XmlSchemaType(name = "string")
    protected WhiteSpaceFacetCodeSimpleType whiteSpaceValueCode;
    @XmlElement(name = "DefinitionText", required = true, nillable = true)
    protected String definitionText;
    @XmlElement(name = "WhiteSpaceFacetAugmentationPoint")
    protected List<Object> whiteSpaceFacetAugmentationPoint;

    /**
     * Gets the value of the whiteSpaceValueCode property.
     * 
     * @return
     *     possible object is
     *     {@link WhiteSpaceFacetCodeSimpleType }
     *     
     */
    public WhiteSpaceFacetCodeSimpleType getWhiteSpaceValueCode() {
        return whiteSpaceValueCode;
    }

    /**
     * Sets the value of the whiteSpaceValueCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhiteSpaceFacetCodeSimpleType }
     *     
     */
    public void setWhiteSpaceValueCode(WhiteSpaceFacetCodeSimpleType value) {
        this.whiteSpaceValueCode = value;
    }

    /**
     * Gets the value of the definitionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefinitionText() {
        return definitionText;
    }

    /**
     * Sets the value of the definitionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefinitionText(String value) {
        this.definitionText = value;
    }

    /**
     * Gets the value of the whiteSpaceFacetAugmentationPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the whiteSpaceFacetAugmentationPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWhiteSpaceFacetAugmentationPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getWhiteSpaceFacetAugmentationPoint() {
        if (whiteSpaceFacetAugmentationPoint == null) {
            whiteSpaceFacetAugmentationPoint = new ArrayList<Object>();
        }
        return this.whiteSpaceFacetAugmentationPoint;
    }

}
